// Generated by https://quicktype.io

export interface Shirt {
  item_id: string;
  item_name: string;
  url: string;
  index: string;
  price: string;
  last_price: string;
  discount: string;
  item_brand: ItemBrand;
  sale_rate: string;
  item_category: ItemCategory;
  item_category2: ItemCategory;
  item_category3: ItemCategory3;
  item_category4: Material;
  item_category5: string;
  images: string[];
  color: string;
}

export enum ItemBrand {
  Mavi = "Mavi",
}

export enum ItemCategory {
  Erkek = "Erkek",
  Unisex = "Unisex",
}

export enum ItemCategory3 {
  Gömlek = "Gömlek",
}

export enum Material {
  Baskili = "Baskılı",
  Denim = "Denim",
  Dokulu = "Dokulu",
  DüzRenk = "Düz Renk",
  Kareli = "Kareli",
  Keten = "Keten",
  Çizgili = "Çizgili",
  ÖrmeGömlek = "Örme Gömlek",
}
